version: "3.8"

services:
  scrum-poker-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrum-poker-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3002
    ports:
      - "3002:3002"
    # If you need any volumes, add them here
    # volumes:
    #   - ./logs:/app/logs
