version: "3.8"

services:
  scrum-poker-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrum-poker-backend
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_CLUSTER=${MONGO_CLUSTER}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
    ports:
      - "3002:3002"