version: '3.8'

services:
  scrum-poker-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrum-poker-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    # If you need any volumes, add them here
    # volumes:
    #   - ./logs:/app/logs